libdvdnavmini depends on libdvdread
This patch fixes the following error messages one might get when
building libdvdnav on W32 using MinGW:

libtool: link:  gcc -shared .libs/libdvdnavmini-4.dll.def
.libs/dvdnav.o .libs/read_cache.o .libs/navigation.o .libs/highlight.o
.libs/searching.o .libs/settings.o .libs/remap.o  -Wl,--whole-archive
../src/vm/.libs/libdvdvm.a -Wl,--no-whole-archive   -O3 -march=i686
- -o .libs/libdvdnavmini-4.dll -Wl,--enable-auto-image-base -Xlinker
- --out-implib -Xlinker .libs/libdvdnavmini.dll.a
Creating library file:
.libs/libdvdnavmini.dll.a.libs/dvdnav.o:dvdnav.c:(.text+0x27):
undefined reference to `DVDCloseFile'

Patch provided by LRN <lrn1986 AT gmail DOT com>, Thanks!